# -*- coding: utf-8 -*-
"""fibo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19XoNsiiLWVyGIx6e-ME0fRQ8gUHA6cuT
"""

# Fibonacci numbers module

def fib(n):    # write Fibonacci series up to n
    a, b = 0, 1
    while a < n:
        print(a, end=' ')
        a, b = b, a+b
    print()

def fib2(n):   # return Fibonacci series up to n
    result = []
    a, b = 0, 1
    while a < n:
        result.append(a)
        a, b = b, a+b
    return result