# -*- coding: utf-8 -*-
"""pert4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z_GhIw_RZ3gDen7k6j-LbUWpev4EPzfM
"""

import sys
sys.ps1

sys.ps2

sys.ps1 = 'C> '

import sys
sys.path.append('/ufs/guido/lib/python')

import fibo, sys
dir(fibo)

dir(sys)

import builtins
dir(builtins)